### ISSUE TITLE
Some weapon icons are broken in the bottom left hud

### ISSUE THREAD

**Issue by mexikoedi** [TTT-2/TTT2#1168] opened 2023-12-11 22:33 UTC
## Your version of TTT2 (mandatory)

- Workshop version from Steam

## Describe the bug (mandatory)

If you pick a weapon the icon of the ammunition is shown in the bottom left hud.
But the weapon: "H.U.G.E-249" has a missing icon.
Custom addons like the "Baby Launcher" and some other addons/weapons also have a missing icon. 

## To reproduce

Steps to reproduce the behaviour:

1. Load into a map
2. Pick up a H.U.G.E-249 or a custom weapon
3. See missing icon

## Expected behaviour

The icon shouldn't be missing and should be replaced by a placeholder icon, something similar or it should be removed if the icon is not available (so that you don't see the pink/black error square).

**Comment by sbzlzh** [comment] 2023-12-12 10:33
The only thing I know so far is that the icon for the HUGE-249 ammo is fixed in the GitHub version. the workshop version has had players responding that they can't see this ammo icon.

![image](https://github.com/TTT-2/TTT2/assets/92261479/30bc0ae9-b6fe-4810-9ecc-a1c00f76691f)

**Comment by Histalek** [comment] 2023-12-12 10:58
I also can't reproduce the issue on the current master.
Weapons with non of the 5 standard types should always get the 'AmmoBox' Icon.

**Comment by TimGoll** [comment] 2023-12-12 11:04
You updated the addon on your server but not on the client. If you have subscribed to TTT2 on steam, you have to restart the game. If you didn't, then make sure that you have an workshop downloader addon installed.

This is a Gmod issue where sometimes new graphics are not yet available on the client

**Comment by mexikoedi** [comment] 2023-12-12 11:18
> You updated the addon on your server but not on the client. If you have subscribed to TTT2 on steam, you have to restart the game. If you didn't, then make sure that you have an workshop downloader addon installed.
> 
> This is a Gmod issue where sometimes new graphics are not yet available on the client

TTT2 updated normally on Steam and I also restarted Gmod after it was done. 
(Tested it on a P2P server.)
Either way if it's working fine then I should also get it to work.

**Comment by saibotk** [comment] 2023-12-12 11:33
Actually the icon was missing, but was included in the weaponstats addon.
will be fixed.

**Comment by TimGoll** [comment] 2023-12-12 11:34
Fixed in #1181. This issue is due to the icon only being part of weaponstats and nobody noticing this because we all use it

**Comment by saibotk** [comment] 2023-12-12 11:41
Thanks for reporting this!

**Closed** 2023-12-12 11:41 UTC
