### ISSUE TITLE
Weapon Switch Bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#407] opened 2019-12-01 18:22 UTC
**Video**
https://www.youtube.com/watch?v=bHaO20lVRvs

**Describe the bug**
So, we found out about some bugs with the new pick-up system for the weapons, the first and most common one (even if it doesn't happen often) basically makes weapons disappear when someone tries to pick them up but sometimes they do reappear when you try to get another one; the second one is more confusing and may be client-side, with this one some players couldn't pick up specific weapons from the floor while others could but it happened very rarely. 

**To Reproduce**
These bugs were very random and hard to replicate

**Expected behaviour**
The weapon should not disappear and be usable 

**Desktop (please complete the following information):**
 - Collection-Link of your Server: https://steamcommunity.com/sharedfiles/filedetails/?id=1806066645
 - Server-Errors in the server console: No error in server console
 - Client-Errors in the developer console:  No error in client console

**Comment by TimGoll** [comment] 2019-12-01 18:27
1. Yes this is known and can't be changed since we have to use an internal hook at we can't influence when it is called. When picking up a new weapon, the old one drops to the ground to remove the problem of disappearing weapons. Sadly this is a workaround to a gmod limitation. (See this featurerequest: https://github.com/Facepunch/garrysmod-requests/issues/1235)

2. This is strange. I can't see a reason why this could happen.

There are still a few minor bugs that I will fix before the update gets released. This might fix your 2nd bug as well. I don't know.

**Comment by TimGoll** [comment] 2019-12-01 21:50
Ok. Your second scenario: did you try to pickup a weapon and this failed before you tried to autopickup the other weapon?

If so, I know why your bug happens. Caused by the same reason as 1, sometimes the pickup hook is a bit unpredictable. Therefore I disabled autopickup for the player that attempts a weapon switch, until the weapon of his desire is in his inventory. If this fails and the weapon stays floating, he can't pickup another weapon with autopickup until he successfully added a weapon into his inventory with the new weapon switch. I could add a timeout though

**Comment by ThePlatinumGhost** [comment] 2019-12-02 09:06
I don't remember but I was trying to replicate bug 1# and after a couple of weapon switches i found out this weapon to be unpickable and without outline
Before this bug every weapon switch worked fine

**Comment by TimGoll** [comment] 2019-12-02 11:10
Without outline? Hmm. I will look at the code but if there is no outline it seems like there is an issue independent of the new weapon switch system. 
Sometimes in vanilla TTT players were also unable to pick up certain weapons. This might be connected to this issue

**Comment by ThePlatinumGhost** [comment] 2019-12-02 12:20
Yes i remember a similar bug in vanilla TTT, i usually fix it by moving the weapon a little bit with the magneto stick
But in the case of the recorded video it didn't work, i must do more test

**Comment by TimGoll** [comment] 2019-12-02 22:15
Okay, I investigated things further. In cases when the weapon can't be picked up, it is because the Pickup hook isn't called at all. Sadly, I don't know why it isn't called. At some point a weapon starts bugging and it can't be picked up anymore.

If someone reading this issue has an idea, please let me know

**Comment by ThePlatinumGhost** [comment] 2019-12-04 14:51
1#)
I'm pretty sure I found out how this disappearing weapon bug happens, and was able to replicate it 90% of the time, I'm not sure it is linked to the other bugs reported as well but it seems to behave differently

https://youtu.be/heXC0OeIf2g

**Comment by TimGoll** [comment] 2019-12-04 14:54
The disappearing thing is because of the error handling. But I see you mean the problem with picking up the weapons, am I right?
And it looks like this problem happens when being crouched?

**Comment by TimGoll** [comment] 2019-12-04 14:55
The thing is, it is entirely possible that the weapons get stuck in thge ammo boyes when crouching and I don't know if there is anything i could do about this. GMOD is just stupid tbh

**Comment by ThePlatinumGhost** [comment] 2019-12-06 16:54
About 1# Bug
I think I understand, it happens when there isn't enough room to drop the weapon, so it disappears. For example when you crouch or in specific locations. I think if this is the problem the solution might be similar to a function that's already present in Vanilla TTT, that is setting an "IF" that checks if there's enough space when you exchange weapons. 
![Half Life  Source Screenshot 2019 12 06 - 16 58 34 49](https://user-images.githubusercontent.com/36534723/70340363-f9770a80-1850-11ea-86e6-053b8ba44a8d.png)
I'm no expert in the subject so I might be wrong but maybe it can help figure this out.

**Comment by TimGoll** [comment] 2019-12-21 19:17
I implemented some workarounds to improve the mentioned problems in https://github.com/TTT-2/TTT2/commit/59b6a0342d60736411b37367528f548110c9e7d3

**Comment by TimGoll** [comment] 2019-12-24 14:11
Huh, is this issue fixed for you? Because we got a better grasp of the problem. It seems to happen when you drop the picked up weapon too early.

**Comment by ThePlatinumGhost** [comment] 2019-12-24 14:13
Yes i closed the issue because the major bug it's fixed for me but if you want a can keep the issue open

**Comment by TimGoll** [comment] 2019-12-24 14:15
doesn't matter too much. We'll try our best to improve this further

**Comment by TimGoll** [comment] 2020-01-03 09:38
Should be fixed with #424
Please reopen if this problem still exists after the merge.

**Closed** 2020-01-03 09:38 UTC
Labels: bug
