### ISSUE TITLE
Random Shop emtpy slots

### ISSUE THREAD

**Issue by TheSuspect2306** [TTT-2/TTT2#949] opened 2021-11-28 15:39 UTC
For example you have 6 Random Items and there is a item that should not be in the Shop, it will not get in the Shop so the Slot will just be empy and you have only 5 Items that also counts for all Shop-able things
how specific it works, i currently have not tested it

**Comment by ZenBre4ker** [comment] 2021-11-28 16:08
I dont fully understand your problem.
So you have items that are not buyable, but still in the random shop or are they there, when you also say, always available in shop but not buyable?

**Comment by TheSuspect2306** [comment] 2021-11-28 16:49
im not really sure what the exact problem is but i think that there are items in the shop that doesnt should be in the shop and thats why they are getting removed and not replaced with a other item and thats why some rounds there are empty slots

**Comment by ZenBre4ker** [comment] 2021-11-28 18:38
Well I cant reproduce what you mean, heres what I tested:
- Deactivated all but 3 items buyable, 1 is always available, random shop set to 2:
=> I always get that one item and 1 of the other 2

- randomshop set to 4
=> I always get all 3 items

**Comment by TheSuspect2306** [comment] 2021-11-29 08:33
alright i've tested it and have come to a conclusion:

in this case i have 3 random things in the shop and put in 5 things, 1 thing is broken and will replace the shop with an empty slot, it must be a issue with .CanBuy = nil

**Comment by TheSuspect2306** [comment] 2021-11-29 08:37
plus there is a kinda error in the console everytime opening the shop while a slot is empty
Equipment item does not have model or material specified: table: 0x015b25837710

**Comment by ZenBre4ker** [comment] 2021-11-29 08:41
Sounds like a broken addon you should post here, as I can only help if I can reproduce your issue. Also try to speak in terms of UI-descriptions, so i know what you did.
In Edit Equipment you can set equipment buyable and always available
![grafik](https://user-images.githubusercontent.com/72046466/143834758-560ef7cf-a74f-444e-85e9-a3a16a547d64.png)

In Random Shop you can enable them and set the number of random equipments:
![grafik](https://user-images.githubusercontent.com/72046466/143834825-911fc741-2296-40dc-8414-85fe3b79bcb3.png)

In edit shops, you can either use a custom shop or the default shop, where you can set canbuy
![grafik](https://user-images.githubusercontent.com/72046466/143834939-1b159aec-7fef-40df-8b75-3f41f5521612.png)

**Comment by TheSuspect2306** [comment] 2021-11-29 11:49
![image](https://user-images.githubusercontent.com/40922292/143862349-e5eadd07-aee7-4f1a-8858-c70ee52d841b.png)
![image](https://user-images.githubusercontent.com/40922292/143862673-2fbdf141-7a6f-4880-8fa9-3f401d667233.png)

simple reproduce: just put the default rifle in the shop / equipment buyable & always available in shop then you will get the same error in the console and a empty slot, is this supposed to happen ?

**Comment by Histalek** [comment] 2022-10-15 12:59
Closing this as i can't reproduce it on current master.

Though i don't see any relevant fixes in our commit history, so please reopen if this is still an issue!

**Closed by Histalek** 2022-10-15 12:59 UTC
Labels: type/bug, status/needs info, priority/low, accepted, status/needs validation, severity/minor
