### ISSUE TITLE
The weapon TargetID not displayed after throw weapon as far.

### ISSUE THREAD

**Issue by Racpy** [TTT-2/TTT2#1038] opened 2023-08-02 11:18 UTC
## Your version of TTT2 (mandatory)
Workshop version from Steam  ( v0.11.6b )

## Describe the bug (mandatory)

Video

https://github.com/TTT-2/TTT2/assets/59442552/34327257-1bea-4d7b-b399-56673d71d455

## To reproduce

Steps to reproduce the behaviour:

1. Pick up any weapon
2. Try to throw your weapon as far as possible
3. Go to the weapon you dropped and check it again

## Expected behaviour

The weapon TargetID should be displayed on the weapon anyway.
If you encounter this problem when a special weapon is dropped, and the weapon does not have an automatic pickup function, some players will not be able to use [pickup key] to pick up the weapon.

## Context (please provide as much as you can)

There is no error with the server and client console.

**Comment by mexikoedi** [comment] 2023-08-02 13:04
This is the wrong repository for this issue.
Here is the correct one: https://github.com/TTT-2/ttt2-weaponstats

(Also try to check your collection/addon folder/... on your server. 
There might be an addon or something else which causes this issue.
I couldn't reproduce this issue on my server.)

**Comment by Racpy** [comment] 2023-08-02 14:16
I try to test without weapon stats still can reproduce this issue.

Here is my collection: https://steamcommunity.com/sharedfiles/filedetails/?id=3001672099
addon folder same as collection, do some change on roles and translation.

**Comment by Racpy** [comment] 2023-08-11 02:15
If you try to move the weapon back to the first point in time when it was dropped, the TargetID may display normal again, the actual position is not known every time, because you have no idea at which point it stopped tracking these entity.

**Comment by Histalek** [comment] 2023-08-11 08:18
It would be interesting to know if this happens in vanilla TTT as well. At least this sounds more like a gmod issue than a TTT2 issue.

**Comment by TimGoll** [comment] 2023-10-05 12:47
This is an issue we tried to fix for the last two years. I don't think we are able to do so, it seems like it is an issue with the game engine itself

**Comment by EntranceJew** [comment] 2023-12-23 20:21
I was able to trigger this myself but I don't believe that distance is the sole factor, because I can also trigger this by exclusively swapping weapons. As observed, the autopickup still functions so its hitbox is still existing. Something about it is failing a trace, however, even though it can be queried for every time the player tries to USE and detected in a radius of the trace result.

**Comment by TimGoll** [comment] 2024-09-21 10:54
Maybe this is fixed with the changes introduced with 0.14.0. If the issues reappear, then please reopen the issue

**Closed by TimGoll** 2024-09-21 10:54 UTC
Labels: type/bug, status/needs validation
