### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#428] opened 2020-01-02 15:50 UTC
When determining the body of the unknown.
[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] gamemodes/terrortown/gamemode/client/cl_main.lua:346: attempt to index a nil value
  1. func - gamemodes/terrortown/gamemode/client/cl_main.lua:346
   2. unknown - lua/includes/extensions/net.lua:32

**Comment by saibotk** [comment] 2020-01-02 15:56
Duplicate of #409

**Closed by saibotk** 2020-01-02 15:56 UTC
