### ISSUE TITLE
It seems that Simplified Chinese and Traditional Chinese don't have automatic line breaks.

### ISSUE THREAD

**Issue by sbzlzh** [TTT-2/TTT2#1110] opened 2023-10-27 16:10 UTC
It's in English:
![image](https://github.com/TTT-2/TTT2/assets/92261479/6ec985f5-c1db-4f12-a4c7-91db1511c799)
This is in simplified Chinese:
![image (1)](https://github.com/TTT-2/TTT2/assets/92261479/0fe6e961-e038-477e-a429-558e42687b08)

**Comment by sbzlzh** [comment] 2023-10-27 16:12
I found the reason. It's the punctuation. For example, if you use a Chinese period and space it in the desired position, then it breaks the line. The fastest way is to use all English punctuation.

**Comment by TimGoll** [comment] 2023-10-27 16:13
> I found the reason. It's the punctuation. For example, if you use a Chinese period and space it in the desired position, then it breaks the line. The fastest way is to use all English punctuation.

that's true, but words without spaces should be broken up as well - so this is still a bugh

**Comment by sbzlzh** [comment] 2023-10-27 16:14
Should I use English punctuation now, or do I go one space at a time :), dabble now that I have the time.

**Comment by sbzlzh** [comment] 2023-10-27 16:24
It seems that Japanese does the same thing, since it uses Chinese symbols

**Comment by Racpy** [comment] 2023-10-27 16:26
I remember the translation changes I made last time, needed to change the number of lines myself within [[text]] to achieve a line break.

If this is a bug, fixing it might result in better translation format consistency, rather than forcing line breaks within [[]] to avoid this outcome.

**Comment by sbzlzh** [comment] 2023-10-27 16:47
> > I found the reason. It's the punctuation. For example, if you use a Chinese period and space it in the desired position, then it breaks the line. The fastest way is to use all English punctuation.
> 
> that's true, but words without spaces should be broken up as well - so this is still a bug

Should I use the English punctuation now, or do I go find them one by one and add spaces :), now that I have time to do that.

**Comment by TimGoll** [comment] 2023-10-27 16:48
> > > I found the reason. It's the punctuation. For example, if you use a Chinese period and space it in the desired position, then it breaks the line. The fastest way is to use all English punctuation.
> > 
> > 
> > that's true, but words without spaces should be broken up as well - so this is still a bug
> 
> Should I use the English punctuation now, or do I go find them one by one and add spaces :), now that I have time to do that.

nah, we will fix it soon

**Comment by sbzlzh** [comment] 2023-10-27 16:48
> > > > I found the reason. It's the punctuation. For example, if you use a Chinese period and space it in the desired position, then it breaks the line. The fastest way is to use all English punctuation.
> > > 
> > > 
> > > that's true, but words without spaces should be broken up as well - so this is still a bug
> > 
> > 
> > Should I use the English punctuation now, or do I go find them one by one and add spaces :), now that I have time to do that.
> 
> nah, we will fix it soon

That's good.

**Comment by TimGoll** [comment] 2023-10-27 18:50
![image](https://github.com/TTT-2/TTT2/assets/13639408/20936a52-b5a6-481a-9e4e-1e839272ba2d)

I tried to fix it. The problem is that chinese characters are not counted as characters. E.g. `该` has a length of 3. I don't know ho to handle it, because I tried to get individual characters.

**Comment by TimGoll** [comment] 2023-10-27 18:56
@sbzlzh do you know by chance if every chinese character consists of three characters?

**Comment by TimGoll** [comment] 2023-10-27 19:02
Phew, I don't think I can solve this issue for now. If I were sure that all characters are chinese, I could just assume that every character uses 3 chars. But as soon as you mix latin characters into the text, it completely breaks. I don't know if there is a nice solution for that.

**Comment by sbzlzh** [comment] 2023-10-27 19:07
> Phew, I don't think I can solve this issue for now. If I were sure that all characters are chinese, I could just assume that every character uses 3 chars. But as soon as you mix latin characters into the text, it completely breaks. I don't know if there is a nice solution for that.

In utf-8, it is true that a Chinese character uses 3 characters. Another way is to replace commas, periods and other such punctuation marks with English ones first, without using Chinese ones.

**Comment by sbzlzh** [comment] 2023-10-27 19:10
So I'm used to using English punctuation in my own plugins, and have to use Chinese conformity in addition to other reasons.

**Comment by TimGoll** [comment] 2023-10-27 20:19
> > Phew, I don't think I can solve this issue for now. If I were sure that all characters are chinese, I could just assume that every character uses 3 chars. But as soon as you mix latin characters into the text, it completely breaks. I don't know if there is a nice solution for that.
> 
> In utf-8, it is true that a Chinese character uses 3 characters. Another way is to replace commas, periods and other such punctuation marks with English ones first, without using Chinese ones.

but this is only a hacky solution that still doesn't work if there are no commas/periods etc

I'd love to have a nice working solution, but the combination of english + chinese in a single string makes it really hard

**Comment by TimGoll** [comment] 2023-10-27 20:45
@saibotk found a solution. I'm probably able to implement it

**Comment by saibotk** [comment] 2023-10-27 20:48
For reference:
`string.len` only handles byte sequences and we just need to use the `utf8` library for this:

https://wiki.facepunch.com/gmod/utf8.len

**Comment by TimGoll** [comment] 2023-10-27 21:39
Fixed in dev, thanks for the report!

**Comment by sbzlzh** [comment] 2023-11-04 10:02
Wouldn't that close the issue?

**Comment by TimGoll** [comment] 2023-11-04 10:02
as soon as the PR is finished and merged, this issue is closed

**Comment by sbzlzh** [comment] 2023-11-04 10:03
Okay, then I'll close this.

**Comment by TimGoll** [comment] 2023-11-04 10:03
> Okay, then I'll close this.

no, this is close us as soon as it is done

**Comment by sbzlzh** [comment] 2023-11-04 10:04
Okay :)

**Comment by sbzlzh** [comment] 2023-11-09 05:02
How is this progressing, is there something missing.

**Comment by TimGoll** [comment] 2023-11-09 07:47
> How is this progressing, is there something missing.

Yes. @saibotk wants me to implement these kinds of line breaks for other languages as well. But I don't have the time to implement that right now

**Comment by sbzlzh** [comment] 2023-11-09 12:01
> > How is this progressing, is there something missing.
> 
> Yes. @saibotk wants me to implement these kinds of line breaks for other languages as well. But I don't have the time to implement that right now

Do you want me to help you implement it? I don't know how, but you can teach me :)

**Comment by sbzlzh** [comment] 2023-12-07 16:09
Is the problem in the body search screen the same problem as in F1.
![image](https://github.com/TTT-2/TTT2/assets/92261479/d5f7d3bb-1663-4307-af9e-725ad6127d98)

**Comment by TimGoll** [comment] 2023-12-07 16:10
yes, we will ship the fix with the 0.12 release in the coming few days. It will fix the issue for all UIs

**Comment by sbzlzh** [comment] 2023-12-07 16:11
That's great.

**Comment by sbzlzh** [comment] 2023-12-12 08:40
![image](https://github.com/TTT-2/TTT2/assets/92261479/7eb2d17d-49e9-43c7-b922-1e135378add8)
![image](https://github.com/TTT-2/TTT2/assets/92261479/eda9b619-c156-458c-93a9-deccd1d15291)
Why does it look a little different to you? It's weird.

**Comment by TimGoll** [comment] 2023-12-12 08:45
![image](https://github.com/TTT-2/TTT2/assets/13639408/75af72b2-d4d4-4c5c-b7f3-b734004a5752)

@saibotk This is indeed still broken. It was working on my last iteration before you took over. Do you know what caused it?

**Comment by saibotk** [comment] 2023-12-12 08:46
Why this looks perfectly fine on your screenshot

**Comment by TimGoll** [comment] 2023-12-12 08:47
![image](https://github.com/TTT-2/TTT2/assets/13639408/7659ace5-4feb-427a-9613-b6bd6d02885d)
no, the linebreak is missing

**Comment by sbzlzh** [comment] 2023-12-12 08:47
Same effect. Mine's basically the same as his.

**Comment by TimGoll** [comment] 2023-12-12 08:47
Well I guess it is not missing, but too late. I had a tolerance of 20% where it started checking for every chararacter. How do you do it?

**Comment by sbzlzh** [comment] 2023-12-12 08:48
![image](https://github.com/TTT-2/TTT2/assets/92261479/85281c5a-1c71-4663-9195-42bcea799821)

**Comment by saibotk** [comment] 2023-12-12 08:48
Will look at that later

**Comment by TimGoll** [comment] 2023-12-12 08:48
@sbzlzh Just to be clear, because I can't read Chinese: There is a lionebreak there that wasn't there before this PR. It is just too late and a few characters are missing?

**Comment by sbzlzh** [comment] 2023-12-12 08:49
> @sbzlzh需要澄清的是，因为我看不懂中文：那里有一个狮子突破，而在此公关之前并不存在。只是太晚了，少了几个字符？

There are other Chinese characters that are not shown in the picture.

**Comment by TimGoll** [comment] 2023-12-12 08:52
Alright, thank you, this is really helpful!

**Comment by saibotk** [comment] 2023-12-12 10:34
![image](https://github.com/TTT-2/TTT2/assets/10776964/736a3fbc-7988-46e2-b1f7-140430813b45)
Yeah i messed up, this looks alright 

Is this correct @sbzlzh ?

**Comment by sbzlzh** [comment] 2023-12-12 10:36
> ![image](https://private-user-images.githubusercontent.com/10776964/289829030-736a3fbc-7988-46e2-b1f7-140430813b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzc1OTcsIm5iZiI6MTcwMjM3NzI5NywicGF0aCI6Ii8xMDc3Njk2NC8yODk4MjkwMzAtNzM2YTNmYmMtNzk4OC00NmUyLWIxZjctMTQwNDMwODEzYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNjZkYmU3NTI4YzE2MWVkYjYyODk0MTJhZDc4ZmQyM2QzZjQyZGNkY2I1ODFmZmM5ZDQ5OWNiZTlkNzU3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1GYV9mpd9q1axnXl4wJeVpJFWKa_2ZdxObpECr1aXcg) Yeah i messed up, this looks alright
> 
> Is this correct @sbzlzh ?
> 
> Ignore missing chars, seems to be a gmod linux font issue

Here's the thing, it shows no missing.

**Comment by TimGoll** [comment] 2023-12-12 10:37
> > ![image](https://private-user-images.githubusercontent.com/10776964/289829030-736a3fbc-7988-46e2-b1f7-140430813b45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzc1OTcsIm5iZiI6MTcwMjM3NzI5NywicGF0aCI6Ii8xMDc3Njk2NC8yODk4MjkwMzAtNzM2YTNmYmMtNzk4OC00NmUyLWIxZjctMTQwNDMwODEzYjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNjZkYmU3NTI4YzE2MWVkYjYyODk0MTJhZDc4ZmQyM2QzZjQyZGNkY2I1ODFmZmM5ZDQ5OWNiZTlkNzU3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1GYV9mpd9q1axnXl4wJeVpJFWKa_2ZdxObpECr1aXcg) Yeah i messed up, this looks alright
> > Is this correct @sbzlzh ?
> > Ignore missing chars, seems to be a gmod linux font issue
> 
> Here's the thing, it shows no missing.

on the left, there are the missing chars

**Comment by sbzlzh** [comment] 2023-12-12 10:38
What is this mess though.

**Comment by TimGoll** [comment] 2023-12-12 10:38
> What is this mess though.

likely a linux issue
I will test it on my windows machine in a moment

**Comment by sbzlzh** [comment] 2023-12-12 10:39
> > What is this mess though.
> 
> likely a linux issue I will test it on my windows machine in a moment

thank you

**Comment by sbzlzh** [comment] 2023-12-12 10:41
Is it a problem with the liunx system? I see some of the fonts are different sizes yeah

![image](https://github.com/TTT-2/TTT2/assets/92261479/69f97466-5825-490b-b645-0ee23e9e24ca)

**Comment by saibotk** [comment] 2023-12-12 10:44
Yes just ignore this

**Comment by TimGoll** [comment] 2023-12-12 10:49
![image](https://github.com/TTT-2/TTT2/assets/13639408/399e7709-8d16-438d-ac3a-103b1058cdfc)
 works on windows, just ignore it

**Comment by sbzlzh** [comment] 2023-12-12 10:52
> ![image](https://private-user-images.githubusercontent.com/13639408/289833260-399e7709-8d16-438d-ac3a-103b1058cdfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzg0NzMsIm5iZiI6MTcwMjM3ODE3MywicGF0aCI6Ii8xMzYzOTQwOC8yODk4MzMyNjAtMzk5ZTc3MDktOGQxNi00MzhkLWFjM2EtMTAzYjEwNThjZGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwNDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOGE4NDNjNTYyNWM5NzkwNTY5YzMwMzYxNTZjNDJkN2U0ZWM3MTZjNjExNzc0OGM1NDg0YTFmMDNmNjRlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZDAvXTPpFDr4Oe9k2XLaH0zZv4bL_xwEDMw8mI3jYk) works on windows, just ignore it

It works great. It's great.
So if you are using Debian or ubuntu can you show the same as in the picture

**Closed** 2023-12-12 11:24 UTC
Labels: type/bug, accepted

**Comment by sbzlzh** [comment] 2023-12-12 15:00
It's solved, and it works well.

**Comment by TimGoll** [comment] 2023-12-12 15:00
We're sorry it took that long. But what seemed like an easy problem was actually quite complex in the end. But it should work now for all languages in all UI elements

**Comment by Racpy** [comment] 2023-12-12 16:57
The new update looks great, no more manual line breaks from translation files.
but the line breaks in body search don’t seem to be perfect?

For example, the strings in the picture will automatically line break.
![1](https://github.com/TTT-2/TTT2/assets/59442552/2a7e19d4-d051-44a7-8a7e-acbe493dbad9)
![2](https://github.com/TTT-2/TTT2/assets/59442552/bc17726b-8c77-4808-b84c-e3d0a231cae0)

**Comment by TimGoll** [comment] 2023-12-12 16:58
> The new update looks great, no more manual line breaks from translation files. but the line breaks in body search don’t seem to be perfect?
> 
> For example, the strings in the picture will automatically line break. ![1](https://private-user-images.githubusercontent.com/59442552/289942388-2a7e19d4-d051-44a7-8a7e-acbe493dbad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA1NjcsIm5iZiI6MTcwMjQwMDI2NywicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NDIzODgtMmE3ZTE5ZDQtZDA1MS00NGE3LThhN2UtYWNiZTQ5M2RiYWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNWQxNDIwN2YyNTgzOWVjZThjZjQ4OGUxNmU1ODBlYjdkZDMyNzg0NmFhYzNiYzM4YzMxNzZlMjhmYzE5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBG-ik97ZH3I37q_ILmDsWr4jRvM1m-ji4yl2r0gbUQ) ![2](https://private-user-images.githubusercontent.com/59442552/289942403-bc17726b-8c77-4808-b84c-e3d0a231cae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA1NjcsIm5iZiI6MTcwMjQwMDI2NywicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NDI0MDMtYmMxNzcyNmItOGM3Ny00ODA4LWI4NGMtZTNkMGEyMzFjYWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWI1MGRhZjMyZTRiYTViYzU2OWE4ZDZmODRhMDkyY2E4MDcxMDY3NmYwYjU5N2ZjOTc5OTMwOGI2YjQ0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VAxtEnVjbnpFk6BzoCIUoQ0b2RSXPB4yNNbn9_V08j4)

probably because there is a whitespace before the curly bracket and whitespaces are preferred when breaking lines

**Comment by Racpy** [comment] 2023-12-12 17:17
> > The new update looks great, no more manual line breaks from translation files. but the line breaks in body search don’t seem to be perfect?
> > For example, the strings in the picture will automatically line break. ![1](https://private-user-images.githubusercontent.com/59442552/289942388-2a7e19d4-d051-44a7-8a7e-acbe493dbad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA1NjcsIm5iZiI6MTcwMjQwMDI2NywicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NDIzODgtMmE3ZTE5ZDQtZDA1MS00NGE3LThhN2UtYWNiZTQ5M2RiYWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNWQxNDIwN2YyNTgzOWVjZThjZjQ4OGUxNmU1ODBlYjdkZDMyNzg0NmFhYzNiYzM4YzMxNzZlMjhmYzE5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBG-ik97ZH3I37q_ILmDsWr4jRvM1m-ji4yl2r0gbUQ) ![2](https://private-user-images.githubusercontent.com/59442552/289942403-bc17726b-8c77-4808-b84c-e3d0a231cae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA1NjcsIm5iZiI6MTcwMjQwMDI2NywicGF0aCI6Ii81OTQ0MjU1Mi8yODk5NDI0MDMtYmMxNzcyNmItOGM3Ny00ODA4LWI4NGMtZTNkMGEyMzFjYWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZWI1MGRhZjMyZTRiYTViYzU2OWE4ZDZmODRhMDkyY2E4MDcxMDY3NmYwYjU5N2ZjOTc5OTMwOGI2YjQ0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VAxtEnVjbnpFk6BzoCIUoQ0b2RSXPB4yNNbn9_V08j4)
> 
> probably because there is a whitespace before the curly bracket and whitespaces are preferred when breaking lines

Hmm, but english seems to display normally as expected.
![3](https://github.com/TTT-2/TTT2/assets/59442552/589eb4fe-87ca-427d-9e1b-69c2b1de0e0d)

**Comment by TimGoll** [comment] 2023-12-12 17:19
becasue english has other whitespaces where i can break the line. If there is a single line break in the text if first tries to split it there. If the line is still too long, it uses the new line break rework.

is is invalid for chinese to remove this whitespace here?

**Comment by Racpy** [comment] 2023-12-12 17:21
> becasue english has other whitespaces where i can break the line. If there is a single line break in the text if first tries to split it there. If the line is still too long, it uses the new line break rework.
> 
> is is invalid for chinese to remove this whitespace here?

If I remove the spaces, there will be no line breaks, but for me I prefer to keep one space before and after the numbers, just like in English. haha

**Comment by TimGoll** [comment] 2023-12-12 17:23
> > becasue english has other whitespaces where i can break the line. If there is a single line break in the text if first tries to split it there. If the line is still too long, it uses the new line break rework.
> > is is invalid for chinese to remove this whitespace here?
> 
> If I remove the spaces, there will be no line breaks, but for me I prefer to keep one space before and after the numbers, just like in English. haha

Is there a chinese character that is a different type of whitespace that could be used here?

**Comment by Racpy** [comment] 2023-12-12 17:38
> > > becasue english has other whitespaces where i can break the line. If there is a single line break in the text if first tries to split it there. If the line is still too long, it uses the new line break rework.
> > > is is invalid for chinese to remove this whitespace here?
> > 
> > 
> > If I remove the spaces, there will be no line breaks, but for me I prefer to keep one space before and after the numbers, just like in English. haha
> 
> Is there a chinese character that is a different type of whitespace that could be used here?

The Traditional Chinese input method can switch to full-width characters. 
In full-width character mode, press the space key to U+3000.

As shown in the picture, but the spaces are a bit large, but it’s better than no spaces.
![4](https://github.com/TTT-2/TTT2/assets/59442552/62c3440e-d890-4960-9b2d-72454e502929)

**Comment by sbzlzh** [comment] 2023-12-12 18:12
![image](https://github.com/TTT-2/TTT2/assets/92261479/4dbb4da6-9725-49e1-a8f2-29217be6177c)
If you remove the trailing spaces it is normal. Is there any other way.
