### ISSUE TITLE
Spawn Editor - LUA errors

### ISSUE THREAD

**Issue by kivvi4** [TTT-2/TTT2#1024] opened 2023-02-28 21:48 UTC
Workshop Edition - v0.11.6b

Description: Multiple LUA errors appear when using the Spawn Editor. Basically breaks the whole tool, no placing, deleting, or increase/decrease ammo. Was working around 2 weeks before the 23rd of February, tried using it at that date and that's when I noticed it broke.

Error Message: 

[TTT2 (Base) - v0.11.6b] 
gamemodes/terrortown/gamemode/client/cl_network_sync.lua:307: attempt to index local 'metadata' (a nil value)
1. NetReadData - gamemodes/terrortown/gamemode/client/cl_network_sync.lua:307
2. func - gamemodes/terrortown/gamemode/client/cl_network_sync.lua:196
3. unknown - lua/includes/extensions/net.lua:33

My Collection: (I use on a joinable session not dedicated server.)

https://steamcommunity.com/sharedfiles/filedetails/?id=2931392337

**Comment by Histalek** [comment] 2023-03-05 15:47
This might be a peer2peer related issue as i can't reproduce this on a dedicated server.

**Comment by kivvi4** [comment] 2023-03-16 20:20
> This might be a peer2peer related issue as i can't reproduce this on a dedicated server.

Yeah, me and my friends will usually switched gamemodes after an hour or 2 of playing, so I don't use a dedicated server as it's easier for us. 

Is there anything I could do on my end to fix it? Or is this for the TTT2 team?

**Comment by Histalek** [comment] 2023-03-21 18:27
> Is there anything I could do on my end to fix it? Or is this for the TTT2 team?

If you don't want to give it a try fixing this, then it's probably on us (or somebody else who wants to debug and fix this).

**Comment by sbzlzh** [comment] 2023-03-28 14:18
You try inserting above 304: if metadata == nil then
        print("Error: Metadata is nil")
        return
    end 
But I'm not sure if s works.

**Comment by NickCloudAT** [comment] 2023-08-17 14:16
To give my 2cents here:

The Spawneditor works just fine for me in peer2peer. It only does not work when I start a SINGLEPLAYER world:
![image](https://github.com/TTT-2/TTT2/assets/20370962/d3b4429e-1c87-474d-b31b-619ec765ce26)

As soon as I set it to 2+ players everything works as expected.

**Comment by kivvi4** [comment] 2023-08-18 02:28
> Contributor

Possibly may have been fixed, I have not been playing gmod but maybe soon we will pick it back up.

**Comment by TimGoll** [comment] 2023-10-24 20:06
I will close this for now. If this happens again, then please reopen the issue

**Closed by TimGoll** 2023-10-24 20:06 UTC
Labels: status/needs info, accepted
