### ISSUE TITLE
Detective doesn't spawn when too many roles are installed.

### ISSUE THREAD

**Issue by LunexKun** [TTT-2/TTT2#477] opened 2020-02-22 16:26 UTC
## Detective doesn't spawn if too many roles are installed and detective subclasses are enabled.

- This was tested with varying amounts of roles installed, the lowest being 16 afaik.
The issue is that, and it doesn't matter if they are enabled or not, if there is too many roles (shinigami, jackal, etc) installed on the server, detectives will NOT spawn IF there are detective subclasses enabled as well.
So if there is a sniffer enabled on the server and there is an amount of roles that is about 16 or more then there will _never_ be a detective.
If all detective subclasses (sniffer, sheriff etc.) are disabled, a normal detective will spawn as usual with the exception of very few rounds (in about 1/10 rounds there will be no detective whatsoever, but I don't think that's an issue).

## "0.6.1b"

- Workshop version from Steam

**Comment by saibotk** [comment] 2020-03-01 01:15
This seems to be fixed with 2827d90d9b76f7607efd80656c577246db2cc8dd

@LunexKun and me did test this on different servers and this seems to work after the increase in role bits.

**Comment by LunexKun** [comment] 2020-03-09 21:44
Okay, so since this didn't seem to be fixed after all, I asked to have this reopened.

Additionally do I think to have found a clue as to where the bug might originate from.

I am currently trying to set up roles, and assign them to a baserole (JUST LIKE THE SHERIFF AND SNIFFER ARE ASSIGNED TO THE DETECTIIVE!)

To do this i tried to copy the following code forrm the sniffer.

function ROLE:Initialize()
roles.SetBaseRole(self, ROLE_DETECTIVE)
end

I obviously replaced the "ROLE_DETECTIVE" with the baserole i wanted to use, in my case "ROLE_CULTIST".

Once I did that neither the cultist, nor the two roles I used this code on spawned anymore.

As soon as I removed the 3 lines they resmed spawning as usual.

This may be me just doing something dumb with code from another role.
But it might also be a clue to the bug we see with the detectives.

**Comment by Wukerr** [comment] 2020-03-10 16:06
I think that role % for detective is broken when there is too many roles, after setting up random to 100% and player % of that role to max 1.00, Detective is not spawning at all, on settings random 100% and role % 0.13 he is spawning once per 3 rounds in amount of 2(+1 Sheriff).  If i change random to 50% he is spawning once per ~8 rounds. 

I think this is caused by too many roles having player percentage ( having ~16 roles with 0.13 player % and random % added is making detective spawning almost never.


 In order to fix it I suggest adding 4 per player %, one for innos, one for traitors, one for detectives and one for new roles. % of new roles will be splitted to per player % of that role, for example if new roles have 0.25 %pp  for 20 player server, there will be only 5 new roles, and if jackal will have 0.20 %pp there will be always one jackal. 

Or if we want the simplest way to fix it add ttt_detective_min_per_player and if it is set to 0.1 there will be always 1 dete for 10 players.

(Btw having Sniffer and Sheriiff is f*ing up the whole thing more, these roles need to have per_detective_% for working perfectly on servers with many roles)

**Comment by LunexKun** [comment] 2020-03-10 16:14
As I said I am currently experimenting with adding a new faction, that also uses a baserole (equivalent to detective) and as soon as I add subroles to it everything breaks and stops spawning.

**Comment by Wukerr** [comment] 2020-03-13 19:31
Changing value of ttt_max_roles_pct to 0.60 will fix everything, because it leaves some space for detective role to spawn, if it is 0 and the server have ~10 new roles it is battle royale for detective to spawn. 60% is optimal, players with no new roles or few new roles will never notice it, but players with many roles will have detective by default. 
I also suggest not making new roles play % to 1.00 or random to 100, it is very buggy, also it is good when they are lower than detective's values.

**Comment by Histalek** [comment] 2020-04-09 09:56
i retested a bit and it seems to me that the sniffer has a problem that the sheriff does not. I'm not sure if this is the whole story -> @LunexKun have you look at how the sniffer uses the baserole stuff or did you look at the sheriff? or both? do they differ?

It looks like as long as the sniffer is enabled no detective will spawn no matter what.
And as long as the sniffer is disabled everything works for me as intended:

sheriff enabled and sniffer disabled
ttt_detective_random 100
ttt_sheriff_random 50
-> every round a detective will spawn, ~50% of the time he is a sheriff

sheriff enabled and sniffer disabled
ttt_detective_random 50
ttt_sheriff_random 100
-> ~50% of the rounds a detective spawns and he will always be a sheriff

if i try the same setup with sheriff and sniffer interchanged no dete will spawn ever.

if anyone could verify this it would be much appreciated!

**Closed** 2020-05-14 18:05 UTC
Labels: accepted, bug, needs info, priority/important
