### ISSUE TITLE
Role TargetID on a player corpse does not update until it is searched again.

### ISSUE THREAD

**Issue by AaronMcKenney** [TTT-2/TTT2#646] opened 2020-09-03 07:25 UTC
## Version
TTT2 Version: **v0.7.3b**
Spy Latest Commit (Used in Steps To Reproduce): **6b7b03d**

## Description
The TargetID of corpses does not sync up properly with their "was_role" field. That is, if the corpse's role is updated post-confirmation, their TargetID will remain unaltered. The TargetID is only updated if a player searches the corpse after the role has been changed.

## Steps To Reproduce
1. Create a game with 7 bots
2. Using ulx menu, set the Convars for the spy such that all spies will be confirmed as traitors and that they will only be revealed if all traitors and spies are dead.
2. Using ulx menu, set Bot01 and Bot02 to be traitors. Set Bot03 to be a spy. Set Bot04 to be a Jackal. Set all other bots to be innocent.
3. Kill Bot 03. Confirm them as a traitor. Notice that their role in the Score Board shows them as a traitor.
4. Kill Bot01 and Bot02. Confirm them both as traitors.
5. Notice that Bot03 is now shown as a spy in the Score Board. Move the crosshair over their corpse. The crosshair will have the traitor icon.

## Expected Behavior
The crosshair in step 5 should be the spy icon.

## Relevant Images
![dead_spy_targetID_is_traitor_1](https://user-images.githubusercontent.com/5722300/92083957-984a7c00-ed7b-11ea-8fa1-00de62f94336.png)
TargetID of Bot03's corpse is a traitor, but the Score Board shows Bot03 as a Spy.

![dead_spy_targetID_is_traitor_2](https://user-images.githubusercontent.com/5722300/92083979-9d0f3000-ed7b-11ea-9055-383845c66a12.png)
Spy Convars used (Spy's role is revealed when every traitor and spy are dead).

**Comment by saibotk** [comment] 2020-09-28 15:59
This seems to be a problem with the spy, which overwrites many hooks to achieve the role jamming.
We are working on a solution for that, but to confirm, that this is not a general issue with TTT2, could you test this again without the spy role installed?

**Comment by AaronMcKenney** [comment] 2020-09-28 18:19
How would I go about testing this without the spy, and how is this related to TTT-2/ttt2-role_spy#23? I also see this issue with the defective role I'm working on, if that helps...

**Comment by saibotk** [comment] 2020-09-28 18:22
The Spy used to break the targetID and it could be the issue you reported, so uninstall the spy and test it with your detective role for example (or just update the spy to the latest workshop version in which this should be fixed)

**Comment by TimGoll** [comment] 2020-09-28 18:22
I think it is more related to role syncing and that roles aren't updated once the role is updated on the server (ie the spy reveal)

**Comment by Histalek** [comment] 2020-09-28 18:35
> I also see this issue with the defective role I'm working on, if that helps...

If your Defective has the base team traitor that would again point to the spy being the culprit

**Comment by AaronMcKenney** [comment] 2020-09-28 18:38
When I have time I'll try to replicate this issue with the defective after removing the spy from my server.

**Comment by AaronMcKenney** [comment] 2020-09-29 07:01
Ok. I have replicated the issue with the Defective role.
To replicate, follow steps that I listed out for Spy, except replace instances of "traitor" with Detective and replace instances of "spy" with Defective.

Screenshots:
![dead_def_targetID_is_det_1](https://user-images.githubusercontent.com/5722300/94522699-e6b93200-01e4-11eb-9236-cf4ec97b4394.png)
![dead_def_targetID_is_det_2](https://user-images.githubusercontent.com/5722300/94522698-e6209b80-01e4-11eb-91dd-b45fb7ac7f8f.png)

There are two possibilities from my point of view:
1. My code for Defective has the same issue as Spy.
2. The issue is a desync between TargetID and Scoreboard.

Code is here (commit 45b2111): https://github.com/AaronMcKenney/ttt2-role_def

**Comment by saibotk** [comment] 2020-09-29 19:06
@AaronMcKenney A tip, to prevent issues like the spy, add some safety checks, to only enable certain hooks, when a defective is actually enabled/selected in a round.
Also the spy code is pretty messy and buggy itself and the TargetID and Scoreboard are not synced, as the TargetID takes it data from the corpse / search result and the Scoreboard uses the general player data (if i remember correctly).
Since you are injecting into the role / confirm hooks, it might me a problem on your side and i would recommend debugging the usage of the https://github.com/AaronMcKenney/ttt2-role_def/blob/45b211106daf3ef2e5004d10e0556614448278b2/lua/terrortown/entities/roles/defective/shared.lua#L432
Hook (probably the reveal hook too), and the client side search result, as the search result is not automatically updated.

**Comment by AaronMcKenney** [comment] 2020-09-29 20:01
@saibotk I currently believe that the safety checks that you have mentioned are already present for this function. Explicitly, neither "corpse.was_role == ROLE_DEFECTIVE" nor "not AllowDetsToInspect()" will be true if a defective isn't present. I'll clean up the function a bit more to make this more apparent. 

> TargetID and Scoreboard are not synced

That's sort of why I filed this issue though? I'm still not sure how TTT-2/ttt2-role_spy#23 could fix this desync (The test requires the Spy to exist), but I could retest with that version of the Spy's code if you wish and update with the results...

**Comment by saibotk** [comment] 2020-09-29 20:07
No this just fixed it for other roles if the spy is not active. The spy still is due for a rework and it wouldn't surprise me if it is still bugged there.

The thing is, we differentiate betweeen the body search result and the general information. And i dont think we should change that, the spy has to adapt to clear the previous body search etc.

In any other case, this would introduce the need to refactor the whole confirm/search/role knowledge interaction and we are quite limited if we still want to be highly compatible.

**Comment by AaronMcKenney** [comment] 2020-09-29 20:11
Ok... for the Defective role I'm working, what I could I do as a workaround? Are there any hooks I could piggyback off of to manually sync the role, and if so which one?

**Comment by saibotk** [comment] 2020-11-04 01:47
Sorry, I do not know at the moment on how to approach this and my time is limited too. You may ask on the Discord for more tips, but for now I am going to close this, as this is indeed not a bug within TTT2.
But thank you for investigating a potential issue!

**Closed by saibotk** 2020-11-04 01:47 UTC
Labels: rejected, severity/minor, type/bug, type/intended behaviour

**Comment by TimGoll** [comment] 2020-11-04 08:31
I'm not sure why you closed this as it is still relevant. It will be fixed as soon as we use your new system to sync the data. Right now this targetID system relies on the confirmation data, which isn't updated in the above described scenarios.

**Comment by saibotk** [comment] 2020-11-04 09:52
No i closed it because this is intended, so not a bug. Also i do believe that the scoreboard and scoreboard information should still be distinct as they are different sources of information

**Comment by TimGoll** [comment] 2020-11-04 09:53
Why is intended that the targetID data isn't updated? In my opinion this is a bug. If the public shared role is changed, it should be updated everywhere. And not everywhere but in targetID.

**Comment by saibotk** [comment] 2020-11-04 09:58
As discussed in my previous messages in this thread, targetid represents the body found data which may be different from the scoreboard data. A body usually does not change its role. If so, it still is important to distinct between both sources of information. They may be "unsynced" which is correct behavior and should be allowed to happen. That is why this is not a bug and also this out of sync issue described in this issue is related to manual interference with the syncing by an addon

**Comment by AaronMcKenney** [comment] 2020-11-04 20:47
That's understandable... but couldn't a hook be added to keep the two in sync?

**Comment by saibotk** [comment] 2020-11-04 20:53
Sadly not, these are two completely different systems that aren't easily synchronized with a hook. You can do that manually, thats for sure, but as i said, atm i cannot give you a detailed explanation on where to sync what.
