### ISSUE TITLE
error radio used

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#376] opened 2019-09-05 11:28 UTC
When you call "c" menu when you bought the radio.

[Trouble in Terrorist Town 2 (Advanced Update) - v0.5.5b] gamemodes/terrortown/gamemode/client/cl_equip.lua:677: attempt to index global 'TRADIO' (a nil value)
1. unknown - gamemodes/terrortown/gamemode/client/cl_equip.lua:677
2. unknown - lua/includes/modules/concommand.lua:54

**Comment by TimGoll** [comment] 2019-09-05 11:29
oof fixed one bug and forgot to make another variable global. Thanks.

**Comment by dok441** [comment] 2019-09-05 12:36
https://www.youtube.com/watch?time_continue=1&v=7_XZ5kBpcms

**Comment by TimGoll** [comment] 2019-09-05 16:43
actually, I can't reproduce this. This works for me as intended and the variable `TRADIO` is already global. Maybe this is caused by another addon, that is bugged since the GMOD update a few days ago? Can you check if there are any errors prior to this error?

**Closed** 2019-10-05 15:30 UTC
Labels: bug, important, invalid
