### ISSUE TITLE
ERROR death_faker

### ISSUE THREAD

**Issue by dok441** [TTT-2/TTT2#444] opened 2020-01-17 16:44 UTC
https://steamcommunity.com/sharedfiles/filedetails/?id=1473581448
[ERROR] addons/weapon_death_faker/lua/weapons/weapon_ttt_fakedeath/hooks.lua:41: attempt to index local 'confirmed' (a boolean value)
  1. fn - addons/weapon_death_faker/lua/weapons/weapon_ttt_fakedeath/hooks.lua:41
   2. Run - addons/ulib/lua/ulib/shared/hook.lua:109
    3. IdentifyBody - gamemodes/terrortown/gamemode/server/sv_corpse.lua:94
     4. ShowSearch - gamemodes/terrortown/gamemode/server/sv_corpse.lua:301
      5. unknown - gamemodes/terrortown/gamemode/server/sv_player.lua:593

**Comment by Histalek** [comment] 2020-01-17 16:47
Could you please describe what was happening when the error occured?

**Comment by TimGoll** [comment] 2020-01-17 16:47
LeBroomer, this is your addon!

**Comment by dok441** [comment] 2020-01-17 16:48
Following from the error, I understand that when confirming the corpse of a fake body, it turns out, I can be wrong, but at first glance everything is obvious.

**Comment by menof36go** [comment] 2020-02-08 00:24
I am 95% sure this is caused by the player having disconnected before the fake body with his uqid was confirmed.

```lua
if not corpse.is_fake and corpse.uqid then
		local confirmed = player.GetByUniqueID(corpse.uqid)
		
		confirmed:SetNWBool("FakedDeath", false)

		local fakeBody = confirmed.fake_corpse

		if not explode:GetBool() or not IsValid(fakeBody) then return end

		confirmed:SetNWBool("FakedDeath", false)
```

**Comment by lebroomer** [comment] 2020-02-10 21:29
It's a problem caused by the death faker addon. I will fix it asap, but since it's not TTT2 related, I will close this issue.

**Closed by lebroomer** 2020-02-10 21:29 UTC
Labels: bug, needs info

**Comment by dok441** [comment] 2020-06-01 14:14
It's been a long time, but the error is still there. And Yes, this is not related to the player's exit, since the player was on the server at this point when this error popped up.
