### ISSUE TITLE
'DNAScannerDistanceFont' isn't a valid font

### ISSUE THREAD

**Issue by DerScherenmann** [TTT-2/TTT2#606] opened 2020-07-04 09:06 UTC
## Disclaimer

If you are missing the following information your issue will be closed!

- v0.7.2b
- At the End of the round the game crashes for all players

Also please make sure to read the [FAQ](https://github.com/TTT-2/TTT2/wiki/faq) first!

## Your version of TTT2 (mandatory)

Leave one of the following:

- Workshop version from Steam v0.7.2b
- Latest GitHub version
- Non-latest GitHub version (please provide what you can to specify)

## Video

If it's a very strange problem, it's better to add a video to see what happens.  
This step can replace the following steps: "Describe the bug", "To reproduce"

## Describe the bug (mandatory)

An error is **not** a description.

## To reproduce

Steps to reproduce the behaviour:

1. Join a server with these addons: https://steamcommunity.com/sharedfiles/filedetails/?id=1854024120
2. Play a round with detective
3. As soon as the round is over or the detective  dies the game crashes

## Expected behaviour

Round end time should continue as normal and next round should start

## Context (please provide as much as you can)

- Collection link of your Server: [e.g. https://steamcommunity.com/sharedfiles/filedetails/?id=1854024120]
- **All** Server errors in the server console:

[Der Scherenmann|2|STEAM_0:1:158435543] Lua Error:

[ERROR] lua/includes/modules/draw.lua:65: 'DNAScannerDistanceFont' isn't a valid font

  1. SetFont - [C]:-1
   2. drawSimpleText - lua/includes/modules/draw.lua:65
    3. AdvancedText - gamemodes/terrortown/gamemode/client/cl_fonts.lua:151
     4. FillScannerScreen - gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua:414
      5. unknown - gamemodes/terrortown/entities/weapons/weapon_ttt_wtester.lua:462

- Client errors in the developer console: same thing as above
- Other addons installed in your servers `addons` folder see collection
- Screenshots

**Comment by TimGoll** [comment] 2020-07-04 09:10
Strange. Because this font definitely exists and the crash does not happen for us. Maybe one of your addons overwrites our DNA scanner?

**Comment by DerScherenmann** [comment] 2020-07-04 10:32
Alright i'll look into it but it worked last week

**Comment by TimGoll** [comment] 2020-07-04 10:38
Hm, the DNA scanner update is older than a week. Maybe another addon updated something?

**Comment by DerScherenmann** [comment] 2020-07-04 19:43
Its not fault of the addons, i tested it without any and it still crashes all clients with the same message as stated above

**Comment by TimGoll** [comment] 2020-07-04 19:47
Very strange because it doesn't happen for us.
I honestly have no idea right now

**Comment by TheNickSkater** [comment] 2020-07-04 20:11
Please be sure that this (https://steamcommunity.com/sharedfiles/filedetails/?id=2141600596) addon is completely removed, as it messes with the default weapon base and breaks the DNA scanner and other weapons completely. Even if this is not the crash cause, still do it.

**Comment by Histalek** [comment] 2020-07-05 09:32
![image](https://user-images.githubusercontent.com/16392835/86529578-fd840d00-beb1-11ea-80aa-fea1a1bbfdd3.png)

Please pay attention to your server console output. In addition to what Nick mentioned you have another incompatible addon installed, which might be causing the problem.

Also i can't reproduce your Issue on a fresh installed server.

**Comment by Histalek** [comment] 2020-07-29 08:15
Further reports indicate that this crash is caused by addons which overwrite the `weapon_tttbase`. Therefore i will close this.

Please feel free to reopen this if you have other leads :)

**Closed by Histalek** 2020-07-29 08:15 UTC
Labels: priority/low, severity/major, status/cannot reproduce, type/bug
