### ISSUE TITLE
Lens and identification bug

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/TTT2#504] opened 2020-04-07 15:28 UTC
I noticed 2 bugs
1) the first concerns the lens on the scoreboard, which has apparently disappeared, after identifying a corpse a semi-transparent lens should appear.

2) the second bug concerns identification information, when you identify a corpse and you are the first to identify it, the information remains on the scoreboard (correctly), while if you are not the first, despite the fact that you check the corpse the information is not saved on the scoreboard (incorrect), the information should be saved on the scoreboard regardless of who identifies first the body

Video prove/explanation
https://youtu.be/hPRJmm-8_zs

**Comment by TimGoll** [comment] 2020-05-05 14:21
1. The lens does appear when a detective searched the corpse. Isn't this the intended behaviour?

2. good spot, I'll fix it.

**Comment by ThePlatinumGhost** [comment] 2020-05-05 14:54
Yes, on vanilla TTT if a Detective identifies a corpse a lens comes out on the scoreboard on the dead person and the person's information is visible to everyone even to those who have not identified the body

**Comment by TimGoll** [comment] 2020-05-05 14:56
> Yes, on vanilla TTT if a Detective identifies a corpse a lens comes out on the scoreboard on the dead person and the person's information is visible to everyone even to those who have not identified the body

Anf this does no longer happen? The information is still shown, isn't it? only the icon is missing?

**Comment by ThePlatinumGhost** [comment] 2020-05-05 14:58
No, it is very confusing, it often does not happen, but in general even when you personally identify the body, the information is not stored in the scoreboard

**Comment by TimGoll** [comment] 2020-05-05 14:59
I'll look into it

**Comment by ThePlatinumGhost** [comment] 2020-05-18 21:16
I don't know if it's correlated but I think so. I found out another thing, some player's role icon aren't correctly displayed. Sometimes it shows the correct icon and other times the "unidentified" icon even if the body is identified, and this happens to some players while others see the correct one, so it's probably client side (i think)

Video
https://youtu.be/Siix4sXtaKA

**Comment by TimGoll** [comment] 2020-05-24 10:55
All of this will be fixed once we rework the confirmation syncing

**Comment by Histalek** [comment] 2024-02-08 15:41
both of these issues should be fixed.
the 1. by #1260 and the 2. by the bodysearch rework and subsequent fixes.

**Closed by Histalek** 2024-02-08 15:41 UTC
Labels: type/bug, keepalive, status/needs validation
