### ISSUE TITLE
Bindings of sprint and team voice chat, team voice chat issue

### ISSUE THREAD

**Issue by Satton2** [TTT-2/TTT2#437] opened 2020-01-06 07:34 UTC
Hello. :3
Well, dok441 already created almost the same Issue (https://github.com/TTT-2/TTT2/issues/350), but I want to create a new one because he asked me for it. ;)
**Note**: it's not a translation of his words.
1) **The default key**
As you know, the default key for the  sprint is `SHIFT`, but it's also a key for the traitors' team voice chat. Why we still have two functions bound to one key? I suggest to change the default key for the traitors' team voice chat _and_ add the option to change the key for it in the TTT2 key binding tab so players can change it to whatever key they want.

2) **The traitors' team voice chat is still on after death**
Honestly, I don't know is this a bug happens only with the default key issue, or it can happen by holding the traitors' team voice chat key until death.
Anyway, if you will use team voice chat and die, sometimes, your voice chat will be still on, and it changes to the normal voice chat which can be quite annoying in some cases, especially when the player doesn't know that his/her voice is still transmitting to the voice chat.

**Comment by TimGoll** [comment] 2020-01-06 07:37
1. The default voicechat key can't be changed by us. However you can change it by yourself in the gmod keybindings menue

2. Interesting. This is a problem we should investigate

**Comment by Satton2** [comment] 2020-01-06 08:13
> The default voicechat key can't be changed by us.

Sad to hear that.
> Iteresting. This is a problem we should investigate

At least, maybe the team voice chat issue will be solved. =)

**Comment by TimGoll** [comment] 2020-01-06 08:15
We still have the low priority plan to move the voice keys to our own binding system. However our binds are not predicted while the gmod binds mostly are. This could be could not be a problem. There are others in our team who know way more about this topic than I do.

**Comment by TimGoll** [comment] 2020-01-23 06:51
Satton2, today is a very happy day for you. Take a look at the referenced PR.

**Comment by Satton2** [comment] 2020-01-23 16:41
Yeah, good to know.

**Comment by saibotk** [comment] 2020-01-25 11:15
Atleast 1. got fixed with 985b3fd1d5cf88fcc34ce8ef95f2195782a1e24d is your second issue still a problem after the changes?

**Comment by menof36go** [comment] 2020-02-08 00:33
There is also a bug where a traitor colleague speaking in global chat will show up as if they were speaking in team chat. Ill investigate

**Comment by saibotk** [comment] 2020-02-10 21:37
Did you find out anything about this bug yet @menof36go ?

**Closed** 2020-02-11 01:31 UTC
Labels: accepted, bug, priority/important

**Comment by menof36go** [comment] 2020-02-11 21:52
> 
> 
> Did you find out anything about this bug yet @menof36go ?

#464 Fixes the bug I mentioned, but I can't reproduce the second bug @Satton2 mentioned. Maybe it was fixed when I reworked the voice functions

**Comment by TimGoll** [comment] 2020-02-11 21:53
> > Did you find out anything about this bug yet @menof36go ?
> 
> #464 Fixes the bug I mentioned, but I can't reproduce the second bug @Satton2 mentioned. Maybe it was fixed when I reworked the voice functions

We fixed it yesterday in the linked commit :)
